djangoPirogov/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('orders.urls')),
]

orders/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('orders/', views.orders, name='orders'),
    path('search/', views.search, name='search'),
    path('clients/', views.clients, name='clients'),
    path('workers/', views.workers, name='workers'),
    path('directory/', views.directory, name='directory'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),

    path('add_technique/', views.add_technique, name='add_technique'),
    path('add_client/', views.add_client, name='add_client'),
    path('add_order/', views.add_order, name='add_order'),
    path('search_order/', views.search_order, name='search_order'),
    path('view_order/<int:order_id>/', views.view_order, name='view_order'),
]

orders/models.py
from django.db import models
from django.conf import settings


class Directory(models.Model):
    name = models.CharField(max_length=255)
    type = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.name} ({self.type})"


class Client(models.Model):
    first_name = models.CharField(max_length=255)
    second_name = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    telephone = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.first_name} {self.second_name} {self.telephone}"


class Order(models.Model):
    description = models.CharField(max_length=255)
    total_cost = models.DecimalField(max_digits=10, decimal_places=2)
    serial_number = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    directory = models.ForeignKey(Directory, on_delete=models.CASCADE)
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)


class Progress(models.Model):
    ORDER_STATUS_CHOICES = [
        ('Принят в работу', 'Принят в работу'),
        ('Готов к выдаче', 'Готов к выдаче'),
        ('Завершен', 'Завершен'),
    ]

    status = models.CharField(max_length=255, choices=ORDER_STATUS_CHOICES)
    notes = models.CharField(max_length=255)
    order = models.ForeignKey('Order', on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        existing_statuses = Progress.objects.filter(order=self.order).values_list('status', flat=True)

        if self.status in existing_statuses:
            raise ValueError('Статус уже существует для этого заказа.')

        # Если заказ уже имеет статус "Готов к выдаче", мы не позволяем установить более ранние статусы
        if 'Готов к выдаче' in existing_statuses and self.status != 'Завершен':
            raise ValueError('Заказ уже готов к выдаче. Можно установить только статус "Завершен".')

        super().save(*args, **kwargs)

orders/forms.py
from django import forms
from .models import Directory, Client, Order, Progress


class LoginForm(forms.Form):
    username = forms.CharField(label='Имя пользователя')
    password = forms.CharField(widget=forms.PasswordInput, label='Пароль')


class DirectoryForm(forms.ModelForm):
    class Meta:
        model = Directory
        fields = ['name', 'type']
        labels = {
            'name': 'Название',
            'type': 'Тип',
        }


class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ['first_name', 'second_name', 'address', 'telephone']
        labels = {
            'first_name': 'Имя',
            'second_name': 'Фамилия',
            'address': 'Адрес',
            'telephone': 'Телефон',
        }


class OrderForm(forms.ModelForm):
    directory = forms.ModelChoiceField(
        queryset=Directory.objects.all(),
        widget=forms.Select(attrs={'onchange': 'check_selection(this);'}),
        required=False,
    )
    create_new_directory = forms.BooleanField(
        label='Создать новую технику',
        required=False,
        widget=forms.CheckboxInput(attrs={'onclick': 'toggle_new_directory();'}),
    )
    new_directory_name = forms.CharField(label='Новая техника (название)', required=False)
    new_directory_type = forms.CharField(label='Тип новой техники', required=False)
    new_total_cost = forms.DecimalField(label='Новая стоимость', required=False)

    class Meta:
        model = Order
        fields = ['description', 'total_cost', 'serial_number', 'directory', 'client']
        labels = {
            'description': 'Описание',
            'total_cost': 'Примерная начальная стоимость',
            'serial_number': 'Серийный номер',
            'directory': 'Техника',
            'client': 'Клиент',
        }

    def clean(self):
        cleaned_data = super().clean()
        directory = cleaned_data.get('directory')
        create_new_directory = cleaned_data.get('create_new_directory')
        new_directory_name = cleaned_data.get('new_directory_name')
        new_directory_type = cleaned_data.get('new_directory_type')

        if not directory and create_new_directory and not (new_directory_name and new_directory_type):
            raise forms.ValidationError('Если создаете новую технику, укажите название и тип')

        return cleaned_data


class SearchOrderForm(forms.Form):
    search_term = forms.CharField(max_length=255, label='Поиск по клиенту или работнику')


class ProgressForm(forms.ModelForm):
    class Meta:
        model = Progress
        fields = ['status', 'notes']
        widgets = {
            'status': forms.Select(choices=Progress.ORDER_STATUS_CHOICES),
        }
        labels = {
            'status': 'Статус',
            'notes': 'Заметки',
        }

class UpdateOrderCostForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['total_cost']

orders/views.py
# orders/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, redirect, get_object_or_404
from .forms import LoginForm, DirectoryForm, ClientForm, OrderForm, SearchOrderForm, ProgressForm, UpdateOrderCostForm
from django.contrib.auth import authenticate, logout, login
from .models import Directory, Client, Order, Progress
from django.contrib.auth.models import User
from django.db.models import Q


def index(request):
    if not request.user.is_authenticated:
        return redirect('login')
    return render(request, 'index.html')


def orders(request):
    if not request.user.is_authenticated:
        return redirect('login')

    all_orders = Order.objects.filter(user=request.user)

    return render(request, 'orders.html', {'orders': all_orders})


def search(request):
    if not request.user.is_authenticated:
        return redirect('login')

    form = SearchOrderForm()

    return render(request, 'search.html', {'form': form})


# orders/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def search_order(request):
    if not request.user.is_authenticated:
        return redirect('login')

    if request.method == 'POST':
        form = SearchOrderForm(request.POST)
        if form.is_valid():
            search_term = form.cleaned_data['search_term']
            orders = Order.objects.filter(
                Q(client__first_name__icontains=search_term) |
                Q(client__second_name__icontains=search_term) |
                Q(user__first_name__icontains=search_term) |
                Q(user__last_name__icontains=search_term)
            )

            # Добавим постраничный вывод
            page = request.GET.get('page', 1)
            paginator = Paginator(orders, 10)  # 10 элементов на странице

            try:
                orders = paginator.page(page)
            except PageNotAnInteger:
                orders = paginator.page(1)
            except EmptyPage:
                orders = paginator.page(paginator.num_pages)

            return render(request, 'search_results.html',
                          {'orders': orders, 'query': search_term, 'paginator': paginator})
    else:
        form = SearchOrderForm()

    return render(request, 'search.html', {'form': form})


def clients(request):
    if not request.user.is_authenticated:
        return redirect('login')

    all_clients = Client.objects.all()

    items_per_page = 10
    paginator = Paginator(all_clients, items_per_page)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, 'clients.html', {'page_obj': page_obj})


def workers(request):
    if not request.user.is_authenticated:
        return redirect('login')

    all_workers = User.objects.all()

    items_per_page = 10
    paginator = Paginator(all_workers, items_per_page)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, 'workers.html', {'page_obj': page_obj})


def directory(request):
    if not request.user.is_authenticated:
        return redirect('login')

    # Получение всех техник
    all_techniques = Directory.objects.all()

    # Определение количества техник на странице
    items_per_page = 10
    paginator = Paginator(all_techniques, items_per_page)

    # Получение номера текущей страницы из параметра запроса
    page_number = request.GET.get('page')
    # Если параметр не указан, используем первую страницу
    page_obj = paginator.get_page(page_number)

    return render(request, 'directory.html', {'page_obj': page_obj})


def login_view(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user:
                login(request, user)
                return redirect('index')  # Замените 'home' на вашу домашнюю страницу
    else:
        form = LoginForm()

    return render(request, 'login.html', {'form': form})


def logout_view(request):
    logout(request)
    return redirect('login')  # Замените 'login' на вашу страницу входа


def add_technique(request):
    if request.method == 'POST':
        form = DirectoryForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('directory')  # Перенаправление на страницу со списком техники
    else:
        form = DirectoryForm()

    return render(request, 'add_technique.html', {'form': form})


def add_client(request):
    if not request.user.is_authenticated:
        return redirect('login')

    if request.method == 'POST':
        form = ClientForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('clients')
    else:
        form = ClientForm()

    return render(request, 'add_client.html', {'form': form})


from .models import Order, Directory
from django.shortcuts import render, redirect
from .forms import OrderForm


def add_order(request):
    if not request.user.is_authenticated:
        return redirect('login')

    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            directory = form.cleaned_data['directory']
            create_new_directory = form.cleaned_data['create_new_directory']
            new_directory_name = form.cleaned_data['new_directory_name']
            new_directory_type = form.cleaned_data['new_directory_type']

            if not directory and create_new_directory and (new_directory_name and new_directory_type):
                directory = Directory.objects.create(name=new_directory_name, type=new_directory_type)

            order = form.save(commit=False)
            order.user = request.user
            order.directory = directory
            order.save()
            return redirect('orders')  # Перенаправьте на страницу с заказами после успешного создания заказа
    else:
        form = OrderForm()

    return render(request, 'add_order.html', {'form': form})


def view_order(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    progress_list = Progress.objects.filter(order=order)
    progress_form = ProgressForm()
    update_cost_form = UpdateOrderCostForm(instance=order)

    if request.method == 'POST':
        progress_form = ProgressForm(request.POST)
        if progress_form.is_valid():
            new_progress = progress_form.save(commit=False)
            new_progress.order = order
            new_progress.save()

        update_cost_form = UpdateOrderCostForm(request.POST, instance=order)
        if update_cost_form.is_valid():
            update_cost_form.save()

    return render(request, 'view_order.html',
                  {'order': order, 'progress_list': progress_list, 'progress_form': progress_form,
                   'update_cost_form': update_cost_form})

orders/templates/add_client.html
{% extends 'base.html' %}

{% block title %}Добавление клиента{% endblock %}

{% block content %}
    <h3>Добавление клиента</h3>
    <a href="{% url 'clients' %}">Вернуться к списку клиентов</a>
    <form method="post" action="{% url 'add_client' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Добавить клиента</button>
    </form>
{% endblock %}

orders/templates/add_order.html
{% extends 'base.html' %}

{% block title %}Добавление заказа{% endblock %}

{% block content %}
    <h3>Добавление заказа</h3>

    <form method="post" action="{% url 'add_order' %}">
        {% csrf_token %}

        {{ form.description.label_tag }}
        {{ form.description }}
        <br>

        {{ form.total_cost.label_tag }}
        {{ form.total_cost }}
        <br>

        {{ form.serial_number.label_tag }}
        {{ form.serial_number }}
        <br>

        <div class="directory-field">
            {{ form.directory.label_tag }}
            {{ form.directory }}
            <br>
        </div>

        <label for="id_create_new_directory">Создать новую технику</label>
        {{ form.create_new_directory }}
        <br>

        <div class="new-directory-fields" style="display: none;">
            {{ form.new_directory_name.label_tag }}
            {{ form.new_directory_name }}
            <br>

            {{ form.new_directory_type.label_tag }}
            {{ form.new_directory_type }}
            <br>
        </div>

        {{ form.client.label_tag }}
        {{ form.client }}
        <br>

        <button type="submit">Оформить заказ</button>
    </form>

    <a href="{% url 'orders' %}">Вернуться к списку заказов</a>

    <script>
        document.addEventListener('DOMContentLoaded', function() {
            var createNewDirectoryCheckbox = document.getElementById('id_create_new_directory');
            var directoryField = document.querySelector('.directory-field');
            var newDirectoryFields = document.querySelector('.new-directory-fields');

            createNewDirectoryCheckbox.addEventListener('change', function() {
                directoryField.style.display = createNewDirectoryCheckbox.checked ? 'none' : 'block';
                newDirectoryFields.style.display = createNewDirectoryCheckbox.checked ? 'block' : 'none';
            });
        });
    </script>
{% endblock %}

orders/templates/add_technique.html
{% extends 'base.html' %}

{% block content %}
    <h2>Добавить технику</h2>
    <a href="{% url 'directory' %}">Вернуться</a>
    <form method="post" action="{% url 'add_technique' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Добавить</button>
    </form>
{% endblock %}

orders/templates/base.html
<!-- orders/templates/base.html -->
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>{% block title %}Меню{% endblock %}</title>
</head>
<body>
    <div class="nav-bar">
        {% if user.is_authenticated %}
            <h2><a class="header" href="{% url 'index' %}">Добро пожаловать, {{ user.first_name }}!</a></h2>
            <div class="actions">
                <button class="menu-button"><a href="{% url 'orders' %}">Заказы</a></button>
                <button class="menu-button"><a href="{% url 'search' %}">Поиск заказа</a></button>
                <button class="menu-button"><a href="{% url 'clients' %}">Клиенты</a></button>
                <button class="menu-button"><a href="{% url 'workers' %}">Работники</a></button>
                <button class="menu-button"><a href="{% url 'directory' %}">Справочник техники</a></button>
                <button class="menu-button"><a href="{% url 'logout' %}">Выйти</a></button>
            </div>
        {% else %}
            <h2><a class="header" href="{% url 'login' %}">Компастер</a></h2>
            <div class="actions">
                <button class="menu-button"><a href="{% url 'login' %}">Авторизоваться</a></button>
            </div>
        {% endif %}
    </div>

    <div class="content">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

orders/templates/clients.html
{% extends 'base.html' %}

{% block title %}Клиенты{% endblock %}

{% block content %}
    <h3>Список клиентов</h3>
    <a href="{% url 'add_client' %}">Добавить клиента</a>

    {% if page_obj.has_other_pages %}
        <div class="pagination">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?page=1">&laquo; первая</a>
                    <a href="?page={{ page_obj.previous_page_number }}">предыдущая</a>
                {% endif %}

                <span class="current">
                    Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
                </span>

                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">следующая</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}">последняя &raquo;</a>
                {% endif %}
            </span>
        </div>
    {% endif %}

    {% if page_obj.object_list %}
        <table>
            <thead>
                <tr>
                    <th>Имя</th>
                    <th>Фамилия</th>
                    <th>Адрес</th>
                    <th>Телефон</th>
                    <th>Дата создания</th>
                </tr>
            </thead>
            <tbody>
                {% for client in page_obj %}
                    <tr>
                        <td>{{ client.first_name }}</td>
                        <td>{{ client.second_name }}</td>
                        <td>{{ client.address }}</td>
                        <td>{{ client.telephone }}</td>
                        <td>{{ client.created_at }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>Список клиентов пуст</p>
    {% endif %}
{% endblock %}

orders/templates/directory.html
{% extends 'base.html' %}

{% block title %}Справочник техники{% endblock %}

{% block content %}
    <h3>Справочник техники</h3>
    <a href="{% url 'add_technique' %}">Добавить технику</a>

    {% if page_obj.has_other_pages %}
        <div class="pagination">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?page=1">&laquo; первая</a>
                    <a href="?page={{ page_obj.previous_page_number }}">предыдущая</a>
                {% endif %}

                <span class="current">
                    Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
                </span>

                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">следующая</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}">последняя &raquo;</a>
                {% endif %}
            </span>
        </div>
    {% endif %}

    {% if page_obj.object_list %}
        <table>
            <thead>
                <tr>
                    <th>Название</th>
                    <th>Тип</th>
                </tr>
            </thead>
            <tbody>
                {% for technique in page_obj %}
                    <tr>
                        <td>{{ technique.name }}</td>
                        <td>{{ technique.type }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>Справочник техники пуст</p>
    {% endif %}
{% endblock %}

orders/templates/index.html
<!-- orders/templates/index.html -->
{% extends 'base.html' %}
{% block title %}Главное меню{% endblock %}

{% block inner_content %}
{% endblock %}

orders/templates/login.html
{% extends 'base.html' %}

{% block title %}Авторизация{% endblock %}


{% block content %}
    <form method="post" action="{% url 'login' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
    </form>
{% endblock %}

orders/templates/orders.html
{% extends 'base.html' %}

{% block title %}Заказы{% endblock %}

{% block content %}
    <h3>Ваши заказы</h3>
    <a href="{% url 'add_order' %}">Оформить новый заказ</a>
    {% if orders %}
        <table>
            <thead>
                <tr>
                    <th>Описание</th>
                    <th>Общая стоимость</th>
                    <th>Серийный номер</th>
                    <th>Дата создания</th>
                    <th>Справочник</th>
                    <th>Клиент</th>
                </tr>
            </thead>
            <tbody>
                {% for order in orders %}
                    <tr>
                        <td>{{ order.description }}</td>
                        <td>{{ order.total_cost }}</td>
                        <td>{{ order.serial_number }}</td>
                        <td>{{ order.created_at }}</td>
                        <td>{{ order.directory.name }}</td>
                        <td>{{ order.client.first_name }} {{ order.client.second_name }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>У вас пока нет заказов.</p>
    {% endif %}
{% endblock %}

orders/templates/search.html
<!-- orders/templates/search.html -->
{% extends 'base.html' %}

{% block title %}Поиск заказа{% endblock %}

{% block content %}
    <h3>Поиск заказа</h3>

    <form method="post" action="{% url 'search_order' %}">
        {% csrf_token %}

        {{ form.search_term.label_tag }}
        {{ form.search_term }}
        <br>

        <button type="submit">Поиск</button>
    </form>

{% endblock %}

orders/templates/search_results.html
<!-- orders/templates/search.html -->
{% extends 'base.html' %}

{% block title %}Поиск заказа{% endblock %}

{% block content %}
    <h3>Поиск заказа</h3>
    {# Добавьте содержимое формы или текст по вашему выбору #}

    <table border="1">
        <thead>
            <tr>
                <th>Описание</th>
                <th>Стоимость</th>
                <th>Серийный номер</th>
                <th>Дата создания</th>
                <th>Техника</th>
                <th>Клиент</th>
                <th>Работник</th>
                <th>Действия</th>
            </tr>
        </thead>
        <tbody>
            {% for order in orders %}
                <tr>
                    <td>{{ order.description }}</td>
                    <td>{{ order.total_cost }}</td>
                    <td>{{ order.serial_number }}</td>
                    <td>{{ order.created_at }}</td>
                    <td>{{ order.directory.name }} ({{ order.directory.type }})</td>
                    <td>{{ order.client.first_name }} {{ order.client.second_name }} ({{ order.client.telephone }})</td>
                    <td>{{ order.user.first_name }} {{ order.user.last_name }}</td>
                    <td><a href="{% url 'view_order' order_id=order.id %}">Просмотр заказа</a></td>

                </tr>
            {% endfor %}
        </tbody>
    </table>

{% endblock %}

orders/templates/view_order.html
<!-- orders/templates/view_order.html -->
{% extends 'base.html' %}

{% block title %}Просмотр заказа{% endblock %}

{% block content %}
    <h3>Просмотр заказа</h3>
    <p><strong>Описание:</strong> {{ order.description }}</p>

    <!-- Выводим текущую стоимость и форму для её изменения -->
    <p><strong>Стоимость:</strong> {{ order.total_cost }}</p>
    <form method="post" action="{% url 'view_order' order_id=order.id %}">
        {% csrf_token %}
        {{ update_cost_form.as_p }}
        <button type="submit">Изменить стоимость</button>
    </form>

    <p><strong>Серийный номер:</strong> {{ order.serial_number }}</p>
    <p><strong>Техника:</strong> {{ order.directory.name }} ({{ order.directory.type }})</p>
    <p><strong>Клиент:</strong> {{ order.client.first_name }} {{ order.client.second_name }} ({{ order.client.telephone }})</p>
    <p><strong>Работник:</strong> {{ order.user.first_name }} {{ order.user.last_name }}</p>

    <h4>Статусы заказа:</h4>
    {% if progress_list %}
        <ul>
            {% for progress in progress_list %}
                <li>{{ progress.status }} - {{ progress.notes }}</li>
            {% endfor %}
        </ul>
    {% else %}
        <p>Нет статусов для этого заказа.</p>
    {% endif %}

    <h4>Добавить новый статус:</h4>
    <form method="post" action="{% url 'view_order' order_id=order.id %}">
        {% csrf_token %}
        {{ progress_form.as_p }}
        <button type="submit">Добавить статус</button>
    </form>

    <a href="{% url 'index' %}">Вернуться на главную</a>
{% endblock %}

orders/templates/workers.html
{% extends 'base.html' %}

{% block title %}Работники{% endblock %}

{% block content %}
    <h3>Список работников</h3>

    {% if page_obj.has_other_pages %}
        <div class="pagination">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?page=1">&laquo; первая</a>
                    <a href="?page={{ page_obj.previous_page_number }}">предыдущая</a>
                {% endif %}

                <span class="current">
                    Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
                </span>

                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">следующая</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}">последняя &raquo;</a>
                {% endif %}
            </span>
        </div>
    {% endif %}

    {% if page_obj.object_list %}
        <table>
            <thead>
                <tr>
                    <th>Имя</th>
                    <th>Фамилия</th>
                    <th>Email</th>
                </tr>
            </thead>
            <tbody>
                {% for worker in page_obj %}
                    <tr>
                        <td>{{ worker.first_name }}</td>
                        <td>{{ worker.last_name }}</td>
                        <td>{{ worker.email }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>Список работников пуст</p>
    {% endif %}
{% endblock %}